#
# Generate a given number of users with an ID starting at a given number
#
# Databases_IndependentStudy (main)*$ python3 generate-users.py 10 1000
# INSERT INTO user_in (userId, firstName, lastName) VALUES (1000, 'Tyler', 'U.')
# INSERT INTO user_in (userId, firstName, lastName) VALUES (1001, 'Christine', 'E.')
# INSERT INTO user_in (userId, firstName, lastName) VALUES (1002, 'Albert', 'J.')
# INSERT INTO user_in (userId, firstName, lastName) VALUES (1003, 'Jeffrey', 'B.')
# INSERT INTO user_in (userId, firstName, lastName) VALUES (1004, 'Juan', 'Y.')
# INSERT INTO user_in (userId, firstName, lastName) VALUES (1005, 'Martha', 'M.')
# INSERT INTO user_in (userId, firstName, lastName) VALUES (1006, 'Jeremy', 'Y.')
# INSERT INTO user_in (userId, firstName, lastName) VALUES (1007, 'Albert', 'H.')
# INSERT INTO user_in (userId, firstName, lastName) VALUES (1008, 'Jean', 'G.')
# INSERT INTO user_in (userId, firstName, lastName) VALUES (1009, 'Arthur', 'O.')
#

import sys
import random

# From https://www.ssa.gov/oact/babynames/decades/century.html

FIRST_NAMES = [
    'James',
    'Mary',
    'John',
    'Patricia',
    'Robert',
    'Jennifer',
    'Michael',
    'Linda',
    'William',
    'Elizabeth',
    'David',
    'Barbara',
    'Richard',
    'Susan',
    'Joseph',
    'Jessica',
    'Thomas',
    'Sarah',
    'Charles',
    'Karen',
    'Christopher',
    'Nancy',
    'Daniel',
    'Lisa',
    'Matthew',
    'Margaret',
    'Anthony',
    'Betty',
    'Donald',
    'Sandra',
    'Mark',
    'Ashley',
    'Paul',
    'Dorothy',
    'Steven',
    'Kimberly',
    'Andrew',
    'Emily',
    'Kenneth',
    'Donna',
    'Joshua',
    'Michelle',
    'Kevin',
    'Carol',
    'Brian',
    'Amanda',
    'George',
    'Melissa',
    'Edward',
    'Deborah',
    'Ronald',
    'Stephanie',
    'Timothy',
    'Rebecca',
    'Jason',
    'Laura',
    'Jeffrey',
    'Sharon',
    'Ryan',
    'Cynthia',
    'Jacob',
    'Kathleen',
    'Gary',
    'Amy',
    'Nicholas',
    'Shirley',
    'Eric',
    'Angela',
    'Jonathan',
    'Helen',
    'Stephen',
    'Anna',
    'Larry',
    'Brenda',
    'Justin',
    'Pamela',
    'Scott',
    'Nicole',
    'Brandon',
    'Samantha',
    'Benjamin',
    'Katherine',
    'Samuel',
    'Emma',
    'Frank',
    'Ruth',
    'Gregory',
    'Christine',
    'Raymond',
    'Catherine',
    'Alexander',
    'Debra',
    'Patrick',
    'Rachel',
    'Jack',
    'Carolyn',
    'Dennis',
    'Janet',
    'Jerry',
    'Virginia',
    'Tyler',
    'Maria',
    'Aaron',
    'Heather',
    'Jose',
    'Diane',
    'Henry',
    'Julie',
    'Adam',
    'Joyce',
    'Douglas',
    'Victoria',
    'Nathan',
    'Kelly',
    'Peter',
    'Christina',
    'Zachary',
    'Lauren',
    'Kyle',
    'Joan',
    'Walter',
    'Evelyn',
    'Harold',
    'Olivia',
    'Jeremy',
    'Judith',
    'Ethan',
    'Megan',
    'Carl',
    'Cheryl',
    'Keith',
    'Martha',
    'Roger',
    'Andrea',
    'Gerald',
    'Frances',
    'Christian',
    'Hannah',
    'Terry',
    'Jacqueline',
    'Sean',
    'Ann',
    'Arthur',
    'Gloria',
    'Austin',
    'Jean',
    'Noah',
    'Kathryn',
    'Lawrence',
    'Alice',
    'Jesse',
    'Teresa',
    'Joe',
    'Sara',
    'Bryan',
    'Janice',
    'Billy',
    'Doris',
    'Jordan',
    'Madison',
    'Albert',
    'Julia',
    'Dylan',
    'Grace',
    'Bruce',
    'Judy',
    'Willie',
    'Abigail',
    'Gabriel',
    'Marie',
    'Alan',
    'Denise',
    'Juan',
    'Beverly',
    'Logan',
    'Amber',
    'Wayne',
    'Theresa',
    'Ralph',
    'Marilyn',
    'Roy',
    'Danielle',
    'Eugene',
    'Diana',
    'Randy',
    'Brittany',
    'Vincent',
    'Natalie',
    'Russell',
    'Sophia',
    'Louis',
    'Rose',
    'Philip',
    'Isabella',
    'Bobby',
    'Alexis',
    'Johnny',
    'Kayla',
    'Bradley',
    'Charlotte'    
]


def gen_users(num, start):
    for i in range(num):
        firstName = random.choice(FIRST_NAMES)
        lastName = random.choice(['A.', 'B.', 'C.', 'D.', 'E.', 'F.', 'G.', 'H.', 'I.', 'J.', 'K.',
                                  'L.', 'M.', 'N.', 'O.', 'P.', 'Q.', 'R.', 'S.', 'T.', 'U.', 'V.',
                                  'W.', 'X.', 'Y.', 'Z.'])
        print(f"INSERT INTO userIn (userID, unameFirst, unameLast) VALUES ({start + i}, '{firstName}', '{lastName}');")


if __name__ == '__main__':
    if len(sys.argv) > 2:
        gen_users(int(sys.argv[1]), int(sys.argv[2]))
    else:
        print("USAGE: generate-users <number of users> <start of ID>")
        
